# Generated by Django 4.0 on 2022-02-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_exam_duration_hr_exam_duration_min'),
        ('enrollee', '0038_alter_enrollee_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanswers',
            name='answer',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='examanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.question'),
        ),
    ]
