# Generated by Django 4.0 on 2022-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_exam_duration_hr_exam_duration_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='picture',
            field=models.ImageField(default='https://euriqastorage.blob.core.windows.net/profilephotos/missing_profile.jpg', upload_to=''),
        ),
    ]
